"""add mixins to TextBlock

Revision ID: 0b2949ee5dfd
Revises: a2296825c753
Create Date: 2026-02-27 21:23:53.929517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b2949ee5dfd'
down_revision: Union[str, Sequence[str], None] = 'a2296825c753'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('textblock', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('textblock', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('textblock', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_textblock_is_deleted'), 'textblock', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_textblock_is_deleted'), table_name='textblock')
    op.drop_column('textblock', 'is_deleted')
    op.drop_column('textblock', 'updated_at')
    op.drop_column('textblock', 'created_at')
    # ### end Alembic commands ###
