"""update news to image_link

Revision ID: 55a16ae2ec37
Revises: 75d3863b517d
Create Date: 2026-01-19 00:35:58.346111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55a16ae2ec37'
down_revision: Union[str, Sequence[str], None] = '75d3863b517d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('announcement_id', sa.UUID(), nullable=False),
    sa.Column('image_link', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('announcement_id')
    )
    op.add_column('news', sa.Column('image_link', sa.String(), nullable=True))
    op.drop_column('news', 'image_name')
    op.drop_column('news', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('news', sa.Column('image_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('news', 'image_link')
    op.drop_table('announcements')
    # ### end Alembic commands ###
