"""add news and textblock

Revision ID: 75d3863b517d
Revises: e7d06e72d86b
Create Date: 2025-11-20 17:10:34.394030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75d3863b517d'
down_revision: Union[str, Sequence[str], None] = 'e7d06e72d86b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('textblock',
    sa.Column('textblock_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('textblock_id')
    )
    op.add_column('news', sa.Column('image_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'image_name')
    op.drop_table('textblock')
    # ### end Alembic commands ###
