"""update TextBlock

Revision ID: a2296825c753
Revises: 8d054d285a7d
Create Date: 2026-02-27 21:22:14.073609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2296825c753'
down_revision: Union[str, Sequence[str], None] = '8d054d285a7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('textblock', sa.Column('slug', sa.String(length=100), nullable=False))
    op.create_index(op.f('ix_textblock_slug'), 'textblock', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_textblock_slug'), table_name='textblock')
    op.drop_column('textblock', 'slug')
    # ### end Alembic commands ###
