"""rework all models

Revision ID: f1e24597de41
Revises: a22edfc583d1
Create Date: 2026-02-23 17:38:57.026660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1e24597de41'
down_revision: Union[str, Sequence[str], None] = 'a22edfc583d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('announcements', 'image_link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('announcements', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.add_column('news', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('textblock', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('textblock', 'body',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('users', 'surname')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('surname', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('textblock', 'body',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('textblock', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('news', 'created_at')
    op.alter_column('announcements', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('announcements', 'image_link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('announcements', 'created_at')
    # ### end Alembic commands ###
