"""add updated_at and is_active fields

Revision ID: fa35c434b66a
Revises: bedef2647cf6
Create Date: 2026-02-24 14:15:59.843086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa35c434b66a'
down_revision: Union[str, Sequence[str], None] = 'bedef2647cf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('news', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('news', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'is_active')
    op.drop_column('news', 'updated_at')
    op.drop_column('announcements', 'updated_at')
    # ### end Alembic commands ###
